apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura
spec:
   replicas: 3
   selector:
     matchLabels:
       app: conversao-temperatura
   template:
     metadata:
       labels:
         app: conversao-temperatura
     spec:
       containers:
         - name: conversaotemperatura
           image: liviamorais/conversao-temperatura:v1
           ports:
             - containerPort: 8080
               protocol: TCP
               name: http