apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura
spec:
  selector:
    app: conversao-temperatura
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  type: LoadBalancer